name: 💡 機能リクエスト / Feature Request
description: 新機能のアイデアを提案してください / Please suggest an idea for this project
title: '[FEATURE] 💡 機能の概要を入力 / Enter feature summary'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        機能リクエストをありがとうございます。以下の情報を記入してください。
        Thank you for your feature request. Please fill in the information below.

  - type: textarea
    id: summary
    attributes:
      label: 🎯 機能の概要 / Feature Summary
      description: どのような機能が欲しいですか？簡潔に説明してください / What feature would you like to see? Please describe concisely
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 🔎 解決する問題 / Problem Statement
      description: この機能はどのような問題を解決しますか？ / What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: 💭 提案する実装方法 / Proposed Implementation
      description: 可能であれば、この機能をどのように実装すべきか提案してください / If possible, suggest how this feature could be implemented
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: 🤔 検討した代替案 / Alternatives Considered
      description: 他にどのような解決策を検討しましたか？ / What other alternatives have you considered?
    validations:
      required: false

  - type: textarea
    id: value
    attributes:
      label: 📊 ビジネス価値 / Business Value
      description: この機能がもたらす価値や利点は何ですか？ / What value or benefits would this feature bring?
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: 🖼️ 参考資料 / References
      description: 関連するスクリーンショット、図、またはリンクを提供してください / Please provide relevant screenshots, diagrams, or links
    validations:
      required: false
